### ISSUE TITLE
alicloud:dcdn/domain:Domain error with cert_type cas(Certificate Management Service) required SSLPri

### ISSUE THREAD

**Issue by williamwangis** [pulumi/pulumi-alicloud#352]
### What happened?

Pulumi runtime: Python
reference to https://www.pulumi.com/registry/packages/alicloud/api-docs/dcdn/domain/

Create a Dynamic CDN domain and got error if cert_type is cas(Certificate Management Service)

```
updating urn:pulumi:prod::<MASKED>::alicloud:dcdn/domain:Domain::<MASKED>: [ERROR] terraform-provider-alicloud@v1.197.0/alicloud/resource_alicloud_dcdn_domain.go:324: Resource speeddcdn.v16cp.me SetDcdnDomainCertificate Failed!!! [SDK alibaba-cloud-sdk-go ERROR]:
    SDKError:
       StatusCode: 400
       Code: SSLPri.MissingParameter
       Message: code: 400, The SSLPri parameter is required. request id: <MASKED>
       Data: {"Code":"SSLPri.MissingParameter","HostId":"dcdn.aliyuncs.com","Message":"The SSLPri parameter is required.","Recommend":"https://next.api.aliyun.com/troubleshoot?q=SSLPri.MissingParameter\u0026product=dcdn","RequestId":"<MASKED>
```

### Expected Behavior

create DCDN with cert_type: cas and cert_name, should not required private SSL

### Steps to reproduce

create Alibaba Cloud DCDN in Python code and run pulumi up

### Output of `pulumi about`

LI
Version      3.54.0
Go Version   go1.20
Go Compiler  gc

Plugins
NAME        VERSION
alicloud    3.30.0
aws         5.21.1
kubernetes  3.23.1
python      unknown

Host
OS       darwin
Version  12.4
Arch     arm64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
